// Vorschlagsliste für die Branchenauswahl bei der Kundensuche (frei ergänzbar über „Andere Branche“).
export const BRANCHEN = [
  "Anlagenbau",
  "Apotheken",
  "Arztpraxen & medizinische Versorgung",
  "Autohäuser & Kfz-Werkstätten",
  "Automobilzulieferer",
  "Bau & Bauunternehmen",
  "Bildung & Weiterbildung",
  "Druck & Verlag",
  "Einzelhandel",
  "Elektroinstallation",
  "Elektrotechnik",
  "Energie & Umwelt",
  "Finanzdienstleistungen",
  "Gastronomie & Hotellerie",
  "Gebäudereinigung",
  "Gebäudetechnik (Heizung/Sanitär/Klima)",
  "Großhandel",
  "Handwerk (Schreiner/Maler/Metallbau …)",
  "Immobilienwirtschaft",
  "Ingenieurbüros & Architekten",
  "IT-Dienstleistungen",
  "Kunststoffverarbeitung",
  "Landwirtschaft & Gartenbau",
  "Lebensmittelproduktion",
  "Logistik & Spedition",
  "Maschinenbau",
  "Marketing & Werbeagenturen",
  "Medizintechnik",
  "Metallverarbeitung",
  "Personaldienstleistungen",
  "Pflege & soziale Dienste",
  "Rechtsberatung & Kanzleien",
  "Reisen & Tourismus",
  "Sicherheitsdienste",
  "Softwareentwicklung",
  "Steuerberatung & Wirtschaftsprüfung",
  "Textilreinigung & Wäscherei",
  "Unternehmensberatung",
  "Versicherungsmakler"
] as const;

export const EMPLOYEE_CLASSES = ["1–9", "10–19", "20–49", "50–99", "100–249"] as const;
